version: '3.9`'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - finance_tracker

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672" 
      - "5673:5672"   
    networks:
      - finance_tracker

  budgeting:
    container_name: budgeting
    build: .
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
    networks:
      - finance_tracker

networks:
  finance_tracker:
    external: true
    name: finance_tracker

volumes:
  mongo-data:
  db:
